### ISSUE TITLE
Mon PC cassai

### ISSUE THREAD

**Issue by Janastinou** [ConfiiiDev/Among-Us-Modded-1.0#1]
sa a cassai mon pc, jeux fai coman ?

**Comment by D0wzy** [comment]
il fo installait avast t con ou koa

**Comment by janast1975** [comment]
javai kortana ankulé

**Comment by janast1975** [comment]
sa marshe toujour pa, koman jouvre pornhub pour mon expausai de franssai zebi

**Comment by Janastinou** [comment]
zaiby sah marsheu, saiti paurnhaub ky bugay
